export const DATA_SEKAI = [
  {
    LEO: {
      id: "leonid",
      groupName:'Leo/Need',
      Theme: "#33AAEE",
      Logo: "leoLogo.png",
      ThemeBg:"LeonidRooftop.jpg",
      LogoText: "LeoneedlogoText.png",
      LineText:"Linetext-ln.png",
      LeadIMG:"bnw_ichika.png",
      Profile:"A band formed by a group of childhood friends who have learned to overcome their differences.",
      Desc:"A unit of four childhood friends, who became estranged after various circumstances. The distance shifts between the four.",
      GroupIMG:"ln_group.png",
      Char: [
        {
          ichika: [
            {
              id: "Ichika",
              fullName: "Hoshino Ichika",
              Color: "#33AAEE",
              image: "3rd_ichika.png",
              bgRoom:"bg_Ichika_room.jpg",
              birthday: "August 11",
              hobbies: ["Listening to Miku songs", "Admiring her cacti"],
              specialty: ["Peeling apples"],
              likedFood: ["Yakisoba Bread"],
              dislikes: ["Thrill Rides"],
            },
          ],
          saki: [
            {
              id: "Saki",
              fullName: "Tenma Saki",
              Color: "#FFDD45",
              image: "3rd_saki.png",
              bgRoom:"bg_Saki_room.jpg",
              birthday: "May 9",
              hobbies: ["Fashion & make-up videos", "Beading"],
              specialty: ["Hairstyling", "Juggling"],
              likedFood: ["Snacks"],
              dislikes: ["Being alone"],
            },
          ],
          Honami: [
            {
              id: "Honami",
              fullName: "Mochizuki Honami",
              Color: "#EE6666",
              image: "3rd_honami.png",
              bgRoom:"bg_Honami_room.jpg",
              birthday: "October 27",
              hobbies: ["Walking her dog", "Gardening"],
              specialty: ["Housekeeping", "Swimming"],
              likedFood: ["Apple pie"],
              dislikes: ["Drawing"],
            },
          ],
          shiho: [
            {
              id: "Shiho",
              fullName: "Hinomori Shiho",
              Color: "#BBDE22",
              image: "3rd_shiho.png",
              bgRoom:"bg_Shiho_room.png",
              birthday: "January 8",
              hobbies: ["Going to girl band gigs", "Playing bass guitar"],
              specialty: ["Calligraphy"],
              likedFood: ["Ramen", "Salisbury Steak"],
              dislikes: ["Drawing"],
            },
          ],
        },
      ],
    },
    MMJ: {
        id: "momojan",
        groupName:'More More Jump',
        Theme: "#6CCB20",
        Logo: "mmjLogo.png",
        LogoText: "mmjLogoText.png",
        LineText:"Linetext-mmj.png",
        ThemeBg:"mmjpark.jpg",
        LeadIMG:"bnw_minori.png",
        Profile:"A unique idol group formed by one girl with a dream, and three other girls who had given up on theirs.",
        Desc:"A girl who wants to become an idol and three girls who faced the harsh reality of being an idol. Will the optimism overcome the obstacles? Will they reach this dream together?",
        GroupIMG:"mmj_group.png",
        Char: [
          {
            minori: [
              {
                id: "Minori",
                fullName: "Hanasato Minori",
                Color: "#FFCDAC",
                image: "3rd_minori.png",
                bgRoom:"bg_Minori_room.jpg",
                birthday: "April 14",
                hobbies: ["Dance covers", "Writing in her diary","Looking after animals"],
                specialty: ["Coming up with catchphrases"],
                likedFood: ["Salmon"],
                dislikes: ["Relaxing activities"],
              },
            ],
            haruka: [
              {
                id: "Haruka",
                fullName: "Kiritani Haruka",
                Color: "#99CDFF",
                image: "3rd_haruka.png",
                bgRoom:"bg_Haruka_room.jpg",
                birthday: "October 5",
                hobbies: ["Collecting penguin-themed merch"],
                specialty: ["Basketball"],
                likedFood: ["Anything sweet"],
                dislikes: ["Idleness"],
              },
            ],
            airi: [
              {
                id: "Airi",
                fullName: "Momoi Airi",
                Color: "#FFA9CC",
                image: "3rd_airi.png",
                bgRoom:"bg_airi_room.png",
                birthday: "March 19",
                hobbies: ["Researching idols", "Shopping"],
                specialty: ["Cooking", "Looking after kids"],
                likedFood: ["Japanese sweets"],
                dislikes: ["Cats (being allergic)"],
              },
            ],
            shizuku: [
              {
                id: "Shizuku",
                fullName: "Hinomori Shizuku",
                Color: "#9AEEDE",
                image: "3rd_shizuku.png",
                bgRoom:"bg_hinomori_room.jpg",
                birthday: "December 6",
                hobbies: ["Reading", "Taking walks"],
                specialty: ["Archery","Embroidery"],
                likedFood: ["Udon noodles", "Tofu skin"],
                dislikes: ["Reading maps","Using computers"],
              },
            ],
          },
        ],
      },
      VBS: {
        id: "vivibus",
        groupName:'Vivid BAD SQUAD',
        Theme: "#EE1166",
        Logo: "vbsLogo.png",
        LogoText: "vbsLogoText.png",
        LineText:"Linetext-vbs.png",
        ThemeBg:"vbspark.jpg",
        LeadIMG:"bnw_kohami.png",
        Profile:"A talented group of street artists who teamed up to surpass a legend.",
        Desc:"Three young talented musicians from different backgrounds and a meek girl. Their ultimate goal is to surpass the “Legend”. Watch them as they rise to the top of the concrete jungle!",
        GroupIMG:"vbs_group.png",
        Char: [
          {
            kohami: [
              {
                id: "Kohane",
                fullName: "Azusawa Kohane",
                Color: "#FF679A",
                image: "3rd_kohane.png",
                bgRoom:"bg_Kohane_room.jpg",
                birthday: "March 2",
                hobbies: ["Looking after her dad's pet snake"],
                specialty: ["Photography"],
                likedFood: ["Peach buns","Sesame Ball"],
                dislikes: ["Public speaking"],
              },
            ],
            an: [
              {
                id: "An",
                fullName: "Shiraishi An",
                Color: "#00BBDC",
                image: "3rd_an.png",
                bgRoom:"bg_An_room.png",
                birthday: "July 26",
                hobbies: ["Growing mint"],
                specialty: ["Making coffee and tea"],
                likedFood: ["Rum raisin ice cream"],
                dislikes: ["Ghosts or Scary stories"],
              },
            ],
            akito: [
              {
                id: "Akito",
                fullName: "Shinonome Akito",
                Color: "#FF7721",
                image: "3rd_akito.png",
                bgRoom:"bg_Akito_room.png",
                birthday: "November 12",
                hobbies: ["Fashion Styling"],
                specialty: ["Beatboxing"],
                likedFood: ["Pancakes","Cheesecake"],
                dislikes: ["Dogs"],
              },
            ],
            toya: [
              {
                id: "Toya",
                fullName: "Aoyagi Toya",
                Color: "#0077DD",
                image: "3rd_toya.png",
                bgRoom:"bg_Toya_room.jpg",
                birthday: "May 25",
                hobbies: ["Reading"],
                specialty: ["Piano","Violin"],
                likedFood: ["Coffee", "Cookies"],
                dislikes: ["Heights"],
              },
            ],
          },
        ],
      },
      WXS: {
        id: "wandasho",
        groupName:'Wonderlands x Showtime',
        Theme: "#FF9900",
        Logo: "wxsLogo.png",
        LogoText: "wxsLogoText.png",
        LineText:"Linetext-wxs.png",
        ThemeBg:"wxsPark.jpg",
        LeadIMG:"bnw_tsukasa.png",
        Profile:"An eccentric musical show unit, proclaiming each day wonderful and rushing out to meet it head on.",
        Desc:"At a popular theme park, a stage stands deserted. These members come together as one for the revival of the stage. Can they bring back the cheer and laughter to the stage?",
        GroupIMG:"wxs_group.png",
        Char: [
          {
            emu: [
              {
                id: "Emu",
                fullName: "Ootori Emu",
                Color: "#FF66BC",
                image: "3rd_emu.png",
                bgRoom:"bg_Emu_room.jpg",
                birthday: "September 9",
                hobbies: ["Exploring the neighborhood"],
                specialty: ["Acrobatics","Foodie"],
                likedFood: ["Taiyaki"],
                dislikes: ["Dusk"],
              },
            ],
            tsukasa: [
              {
                id: "Tsukasa",
                fullName: "Tenma Tsukasa",
                Color: "#FFBB00",
                image: "3rd_tsukasa.png",
                bgRoom:"bg_Tsukasa_room.jpg",
                birthday: "May 17",
                hobbies: ["Musicals","Making costumes"],
                specialty: ["Striking cool poses","Piano"],
                likedFood: ["Acqua pazza","Ginger fried pork"],
                dislikes: ["Bugs (especially centipedes and millipedes)"],
              },
            ],
            nene: [
              {
                id: "Nene",
                fullName: "Kusanagi Nene",
                Color: "#34DD9A",
                image: "3rd_nene.png",
                bgRoom:"bg_Nene_room.jpg",
                birthday: "July 20",
                hobbies: ["Fighting games","Musicals","Movies"],
                specialty: ["Singing","Technology"],
                likedFood: ["Grapefruit"],
                dislikes: ["Crowded places"],
              },
            ],
            rui: [
              {
                id: "Rui",
                fullName: "Kamishiro Rui",
                Color: "#BB88ED",
                image: "3rd_rui.png",
                bgRoom:"bg_Rui_room.jpg",
                birthday: "June 24",
                hobbies: ["Planning shows","Balloon art"],
                specialty: ["Inventing"],
                likedFood: ["Soda candy"],
                dislikes: ["Cleaning","Menial tasks"],
              },
            ],
          },
        ],
      },
      NIJI: {
        id: "25ji",
        groupName:' 25-ji, Nightcord de',
        Theme: "#884499",
        Logo: "25jiLogo.png",
        LogoText: "25jiLogoText.png",
        LineText:"Linetext-n25.png",
        ThemeBg:"25jiPark.jpg",
        LeadIMG:"bnw_kanade.png",
        Profile:"A mysterious music circle that operates at 1:00 AM (25:00), and whose identities are shrouded in mystery.",
        Desc:'Unaware of what each other looks like or their own names, a circle of friends meet online using the chat tool "Nightcord" to make songs together.',
        GroupIMG:"nigo_group.png",
        Char: [
          {
            kanade: [
              {
                id: "Kanade",
                fullName: "Yoisaki Kanade",
                Color: "#BB6588",
                image: "3rd_kanade.png",
                bgRoom:"bg_Kanade_room.jpg",
                birthday: "February 10",
                hobbies: ["Finding new music to listen to","Movies","Manga","Anime","Art"],
                specialty: ["An innate ability to accurately track time"],
                likedFood: ["Instant noodles","Canned food"],
                dislikes: ["Direct sunlight","Housework"],
              },
            ],
            mayufu: [
              {
                id: "Mafuyu",
                fullName: "Asahina Mafuyu",
                Color: "#8889CC",
                image: "3rd_mafuyu.png",
                bgRoom:"bg_Mafuyu_room.jpg",
                birthday: "January 27",
                hobbies: ["Aquarium"],
                specialty: ["Speaking English"],
                likedFood: ["Mom's home cooking"],
                dislikes: ["Not Sure"],
              },
            ],
            ena: [
              {
                id: "Ena",
                fullName: "Shinonome Ena",
                Color: "#CCAA87",
                image: "3rd_ena.png",
                bgRoom:"bg_Ena_room.jpg",
                birthday: "April 30",
                hobbies: ["Drawing","Taking selfies","Social media","Egosurfing"],
                specialty: ["Researching fashion accessories","Picking out the best cooking ingredients"],
                likedFood: ["Pancakes","Cheesecake"],
                dislikes: ["Getting up in the morning"],
              },
            ],
            mizuki: [
              {
                id: "Mizuki",
                fullName: "Akiyama Mizuki",
                Color: "#E4A8CA",
                image: "3rd_mizuki.png",
                bgRoom:"bg_Mizuki_room.jpg",
                birthday: "August 27",
                hobbies: ["Making Videos","Collages"],
                specialty: ["Redesigning clothes"],
                likedFood: ["Curry rice","French fries"],
                dislikes: ["Foods that are too hot"],
              },
            ],
          },
        ],
      },
  },
];
